[package]
name = "zed_brave_search_context_server"
version = "0.0.1"
edition = "2021"
publish = false
license = "MIT"

[lib]
path = "src/brave_search_context_server.rs"
crate-type = ["cdylib"]

[dependencies]
serde = "1.0"
zed_extension_api = "0.2.0"
